name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11' # You can change this to the version you need (e.g., 8, 17, etc.)

    - name: Compile Java code
      run: javac AddNumbers.java

    - name: Run Java program
      run: java AddNumbers

